import { prisma } from "@/lib/prisma";
import RegisterForm from "./RegisterForm";

export default async function RegisterPage() {
  // @ts-ignore - Prisma client needs to be regenerated by restarting TS Server
  const banner = await prisma.banner.findFirst({
    where: { location: "account_register", isActive: true },
    orderBy: { createdAt: 'desc' }
  });

  const bannerImageUrl = banner?.imageUrl || "https://picsum.photos/seed/account-register/800/1000";
  const bannerTitle = banner?.title || "Jadilah Bagian";

  return <RegisterForm bannerImageUrl={bannerImageUrl} bannerTitle={bannerTitle} />;
}
