import { prisma } from "@/lib/prisma";
import ForgotPasswordForm from "./ForgotPasswordForm";

export default async function ForgotPasswordPage() {
  // @ts-ignore - Prisma client needs to be regenerated by restarting TS Server
  const banner = await prisma.banner.findFirst({
    where: { location: "account_forgot", isActive: true },
    orderBy: { createdAt: 'desc' }
  });

  const bannerImageUrl = banner?.imageUrl || "https://picsum.photos/seed/account-forgot/800/1000";
  const bannerTitle = banner?.title || "Pemulihan Akun";

  return <ForgotPasswordForm bannerImageUrl={bannerImageUrl} bannerTitle={bannerTitle} />;
}
