import { prisma } from "@/lib/prisma";
import LoginForm from "./LoginForm";

export default async function AccountPage() {
  // @ts-ignore - Prisma client needs to be regenerated by restarting TS Server
  const banner = await prisma.banner.findFirst({
    where: { location: "account_login", isActive: true },
    orderBy: { createdAt: 'desc' }
  });

  const bannerImageUrl = banner?.imageUrl || "https://picsum.photos/seed/account-fashion/800/1000";
  const bannerTitle = banner?.title || "Anggota Eksklusif";

  return <LoginForm bannerImageUrl={bannerImageUrl} bannerTitle={bannerTitle} />;
}
